name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Node.js environment using the official Node.js 22 version
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    # Step 3: Set Yarn version to Berry
    - name: Set Yarn version to Berry
      run: yarn set version berry

    # Step 4: Install dependencies
    - name: Install dependencies
      run: yarn install

    # Step 5: Build the React app
    - name: Build React app
      run: yarn build

    # Step 6: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
